name: Node.js CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
      - main

jobs:
  builds:
    runs_on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x,20.x,22.x]

    steps:
      - name: Checkout repository
        uses: actions/setup-node@v2

      - name: Set up Node.jobs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
      
      - name: Install dependencies
        run: npm Install
      
      - name: Run tests
        run: npm test
